bloomFilterPath: "./data/idfa1.csv"
nodes:
  - id: "123"
    uri: "ubuntu-s-1vcpu-2gb-fra1-01"
    replicationURI: ""
    cpuCores: 1
    memoryLimit: 2
    networkLimit: 1
  - id: "ubuntu-s-1vcpu-2gb-fra1-02"
    uri: "134.209.244.237"
    replicationURI: ""
    cpuCores: 1
    memoryLimit: 2
    networkLimit: 1
  - id: "ubuntu-s-1vcpu-2gb-fra1-03"
    uri: "46.101.123.0"
    replicationURI: ""
    cpuCores: 1
    memoryLimit: 2
    networkLimit: 1
