global:
  scrape_interval: 15s # How frequently to scrape targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ] # Prometheus itself
  - job_name: 'bloomnode'
    metrics_path: /metrics
    static_configs:
      - targets: [
        'app_1:9000',
        'app_2:9000',
        'app_3:9000',
        'app_4:9000',
      ]
  - job_name: "nodeexporter"
    static_configs:
      - targets: [
        '161.35.74.38:9100',
        '134.209.244.237:9100',
        '46.101.123.0:9100',
      ]
  - job_name: 'prod'
    metrics_path: /metrics
    static_configs:
      - targets: [
        '161.35.74.38:9000',
        '134.209.244.237:9000',
        '46.101.123.0:9000',
      ]