// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: bloom.proto

package bloomproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_bloom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bloom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_bloom_proto_rawDescGZIP(), []int{0}
}

func (x *TestRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPresent     bool                   `protobuf:"varint,2,opt,name=isPresent,proto3" json:"isPresent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_bloom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bloom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_bloom_proto_rawDescGZIP(), []int{1}
}

func (x *TestResponse) GetIsPresent() bool {
	if x != nil {
		return x.IsPresent
	}
	return false
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_bloom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bloom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_bloom_proto_rawDescGZIP(), []int{2}
}

func (x *InsertRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_bloom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bloom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_bloom_proto_rawDescGZIP(), []int{3}
}

type PrepareBloomFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElementsCount int64                  `protobuf:"varint,1,opt,name=elementsCount,proto3" json:"elementsCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareBloomFilterRequest) Reset() {
	*x = PrepareBloomFilterRequest{}
	mi := &file_bloom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareBloomFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareBloomFilterRequest) ProtoMessage() {}

func (x *PrepareBloomFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bloom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareBloomFilterRequest.ProtoReflect.Descriptor instead.
func (*PrepareBloomFilterRequest) Descriptor() ([]byte, []int) {
	return file_bloom_proto_rawDescGZIP(), []int{4}
}

func (x *PrepareBloomFilterRequest) GetElementsCount() int64 {
	if x != nil {
		return x.ElementsCount
	}
	return 0
}

type PrepareBloomFilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareBloomFilterResponse) Reset() {
	*x = PrepareBloomFilterResponse{}
	mi := &file_bloom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareBloomFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareBloomFilterResponse) ProtoMessage() {}

func (x *PrepareBloomFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bloom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareBloomFilterResponse.ProtoReflect.Descriptor instead.
func (*PrepareBloomFilterResponse) Descriptor() ([]byte, []int) {
	return file_bloom_proto_rawDescGZIP(), []int{5}
}

var File_bloom_proto protoreflect.FileDescriptor

const file_bloom_proto_rawDesc = "" +
	"\n" +
	"\vbloom.proto\x12\vbloom_proto\"\x1f\n" +
	"\vTestRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\",\n" +
	"\fTestResponse\x12\x1c\n" +
	"\tisPresent\x18\x02 \x01(\bR\tisPresent\"!\n" +
	"\rInsertRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"\x10\n" +
	"\x0eInsertResponse\"A\n" +
	"\x19PrepareBloomFilterRequest\x12$\n" +
	"\relementsCount\x18\x01 \x01(\x03R\relementsCount\"\x1c\n" +
	"\x1aPrepareBloomFilterResponse2\x81\x02\n" +
	"\x16DistributedBloomFilter\x12;\n" +
	"\x04Test\x12\x18.bloom_proto.TestRequest\x1a\x19.bloom_proto.TestResponse\x12C\n" +
	"\x06Insert\x12\x1a.bloom_proto.InsertRequest\x1a\x1b.bloom_proto.InsertResponse(\x01\x12e\n" +
	"\x12PrepareBloomFilter\x12&.bloom_proto.PrepareBloomFilterRequest\x1a'.bloom_proto.PrepareBloomFilterResponseB\x0eZ\f./bloomprotob\x06proto3"

var (
	file_bloom_proto_rawDescOnce sync.Once
	file_bloom_proto_rawDescData []byte
)

func file_bloom_proto_rawDescGZIP() []byte {
	file_bloom_proto_rawDescOnce.Do(func() {
		file_bloom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bloom_proto_rawDesc), len(file_bloom_proto_rawDesc)))
	})
	return file_bloom_proto_rawDescData
}

var file_bloom_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bloom_proto_goTypes = []any{
	(*TestRequest)(nil),                // 0: bloom_proto.TestRequest
	(*TestResponse)(nil),               // 1: bloom_proto.TestResponse
	(*InsertRequest)(nil),              // 2: bloom_proto.InsertRequest
	(*InsertResponse)(nil),             // 3: bloom_proto.InsertResponse
	(*PrepareBloomFilterRequest)(nil),  // 4: bloom_proto.PrepareBloomFilterRequest
	(*PrepareBloomFilterResponse)(nil), // 5: bloom_proto.PrepareBloomFilterResponse
}
var file_bloom_proto_depIdxs = []int32{
	0, // 0: bloom_proto.DistributedBloomFilter.Test:input_type -> bloom_proto.TestRequest
	2, // 1: bloom_proto.DistributedBloomFilter.Insert:input_type -> bloom_proto.InsertRequest
	4, // 2: bloom_proto.DistributedBloomFilter.PrepareBloomFilter:input_type -> bloom_proto.PrepareBloomFilterRequest
	1, // 3: bloom_proto.DistributedBloomFilter.Test:output_type -> bloom_proto.TestResponse
	3, // 4: bloom_proto.DistributedBloomFilter.Insert:output_type -> bloom_proto.InsertResponse
	5, // 5: bloom_proto.DistributedBloomFilter.PrepareBloomFilter:output_type -> bloom_proto.PrepareBloomFilterResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bloom_proto_init() }
func file_bloom_proto_init() {
	if File_bloom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bloom_proto_rawDesc), len(file_bloom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bloom_proto_goTypes,
		DependencyIndexes: file_bloom_proto_depIdxs,
		MessageInfos:      file_bloom_proto_msgTypes,
	}.Build()
	File_bloom_proto = out.File
	file_bloom_proto_goTypes = nil
	file_bloom_proto_depIdxs = nil
}
