// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: bloom.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_bloom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bloom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_bloom_proto_rawDescGZIP(), []int{0}
}

func (x *TestRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPresent     bool                   `protobuf:"varint,2,opt,name=isPresent,proto3" json:"isPresent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_bloom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bloom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_bloom_proto_rawDescGZIP(), []int{1}
}

func (x *TestResponse) GetIsPresent() bool {
	if x != nil {
		return x.IsPresent
	}
	return false
}

var File_bloom_proto protoreflect.FileDescriptor

const file_bloom_proto_rawDesc = "" +
	"\n" +
	"\vbloom.proto\x12\x05proto\"\x1f\n" +
	"\vTestRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\",\n" +
	"\fTestResponse\x12\x1c\n" +
	"\tisPresent\x18\x02 \x01(\bR\tisPresent2I\n" +
	"\x16DistributedBloomFilter\x12/\n" +
	"\x04Test\x12\x12.proto.TestRequest\x1a\x13.proto.TestResponseB\tZ\a./protob\x06proto3"

var (
	file_bloom_proto_rawDescOnce sync.Once
	file_bloom_proto_rawDescData []byte
)

func file_bloom_proto_rawDescGZIP() []byte {
	file_bloom_proto_rawDescOnce.Do(func() {
		file_bloom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bloom_proto_rawDesc), len(file_bloom_proto_rawDesc)))
	})
	return file_bloom_proto_rawDescData
}

var file_bloom_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bloom_proto_goTypes = []any{
	(*TestRequest)(nil),  // 0: proto.TestRequest
	(*TestResponse)(nil), // 1: proto.TestResponse
}
var file_bloom_proto_depIdxs = []int32{
	0, // 0: proto.DistributedBloomFilter.Test:input_type -> proto.TestRequest
	1, // 1: proto.DistributedBloomFilter.Test:output_type -> proto.TestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bloom_proto_init() }
func file_bloom_proto_init() {
	if File_bloom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bloom_proto_rawDesc), len(file_bloom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bloom_proto_goTypes,
		DependencyIndexes: file_bloom_proto_depIdxs,
		MessageInfos:      file_bloom_proto_msgTypes,
	}.Build()
	File_bloom_proto = out.File
	file_bloom_proto_goTypes = nil
	file_bloom_proto_depIdxs = nil
}
